# Programming in TensorFlow 2.0

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.1.0'

#Defining a Tensor

In [3]:
tensor = tf.constant([[1,2],[2,3]])

In [4]:
tensor # Tensors Multi Dimensional array 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [5]:
tensor.shape

TensorShape([2, 2])

In [9]:
tensor.numpy()

array([[1, 2],
       [2, 3]], dtype=int32)

In [11]:
numpy_array = np.array([[1,2],[3,4]])

In [12]:
numpy_to_tensor = tf.constant(numpy_array)

In [13]:
tensor + 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [7, 8]], dtype=int32)>

In [14]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 6]], dtype=int32)>

In [15]:
np.square(tensor)

array([[1, 4],
       [4, 9]], dtype=int32)

In [16]:
np.dot(tensor, numpy_to_tensor)

array([[ 7, 10],
       [11, 16]])

In [17]:
tensor[0,0].assign(200)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [18]:
tensor_variable = tf.Variable(tensor)

In [19]:
tensor_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [21]:
tensor_variable[0,0].assign(100) #Value can be changed

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[100,   2],
       [  2,   3]], dtype=int32)>

#ML Models

In [23]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(6, activation='linear', input_shape=[8]),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(4, activation='softmax')
    
])

In [24]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 28        
Total params: 124
Trainable params: 124
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(train_features, train_labels, epochs=10)

NameError: name 'train_features' is not defined